name: my_wellbeing
description: Keeping track of your emotional wellbeing.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0-dev.4.0.flutter-1103600280 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  auto_size_text: ^2.1.0
  simple_animations: ^1.3.4

enable-experiment:
  - extension-methods

dev_dependencies:
  flutter_test:
    sdk: flutter
  keyboard_avoider: ^0.1.2
  rect_getter: ^0.0.1
  shared_preferences: ^0.5.4+1

flutter:
  fonts:
    - family: Playfair
      fonts:
        - asset: fonts/PlayfairDisplay-Regular.ttf
        - asset: fonts/PlayfairDisplay-Bold.ttf
          weight: 700
  uses-material-design: true